#!/usr/bin/env bash
# Verifies real multichannel playback on the device.
#
# This is the test that matters most for this project, because the phone has no platform decoder
# for AC3, EAC3, TrueHD or DTS - the bundled FFmpeg extension is the only thing that can play them.
# The clips are generated by tools/make-host-test-media.sh as 5.1 (6-channel) so that a stereo
# collapse or a dropped channel is detectable, not just theoretical.
#
# Non-destructive: pushes files into a project-owned folder and plays them. No data is cleared.
set -uo pipefail

ADB="${ADB:-$HOME/Library/Android/sdk/platform-tools/adb}"
PKG_DEBUG="com.gan.spatialplayer.debug"
ACT_SMOKE="$PKG_DEBUG/com.gan.spatialplayer.SmokeTestActivity"
ACT_TRACKS="$PKG_DEBUG/com.gan.spatialplayer.SmokeTrackProbeActivity"
MEDIA_DIR="/sdcard/Movies/SpatialPlayerTest"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="${OUT_DIR:-$ROOT/smoke/out}"
HOST_MEDIA="$ROOT/smoke/media"

PASS=0; FAIL=0; SKIP=0
mkdir -p "$OUT_DIR"

say()  { printf '\n\033[1m=== %s ===\033[0m\n' "$1"; }
pass() { printf '  \033[32mPASS\033[0m %s\n' "$1"; PASS=$((PASS+1)); }
fail() { printf '  \033[31mFAIL\033[0m %s\n' "$1"; FAIL=$((FAIL+1)); }
skip() { printf '  \033[33mSKIP\033[0m %s\n' "$1"; SKIP=$((SKIP+1)); }
info() { printf '  ·  %s\n' "$1"; }

sh_()  { "$ADB" shell "$@" 2>/dev/null | tr -d '\r'; }
adb_() { "$ADB" "$@" 2>/dev/null | tr -d '\r'; }

# `dumpsys window` contains several focus records including a stale `mCurrentFocus=null`, so scan
# for the last non-null one instead of taking the first match.
focused_window() {
  sh_ dumpsys window | grep -oE "mCurrentFocus=Window\{[^}]*\}" | grep -v "null" | tail -1
}

# ---------------------------------------------------------------------------
say "preflight"
if [ "$(adb_ get-state)" != "device" ]; then
  fail "no authorised device"
  exit 1
fi
pass "device: $(sh_ getprop ro.product.model) (API $(sh_ getprop ro.build.version.sdk))"

LOCKED="no"
if sh_ dumpsys window | grep -q "isKeyguardShowing=true"; then LOCKED="yes"; fi
if [ "$LOCKED" = "yes" ]; then
  fail "device is locked — playback cannot start"
  exit 1
fi
pass "device unlocked"

if ! ls "$HOST_MEDIA"/*.mkv >/dev/null 2>&1; then
  fail "no host test media in $HOST_MEDIA — run tools/make-host-test-media.sh"
  exit 1
fi

say "push multichannel clips"
sh_ "mkdir -p $MEDIA_DIR"
for f in "$HOST_MEDIA"/*.mkv "$HOST_MEDIA"/*.mka; do
  [ -f "$f" ] || continue
  name=$(basename "$f")
  # Skip files already present with the same size.
  want=$(wc -c < "$f" | tr -d ' ')
  have=$(sh_ "stat -c %s $MEDIA_DIR/$name 2>/dev/null || echo 0")
  if [ "$want" = "$have" ]; then
    info "$name already present"
  else
    adb_ push "$f" "$MEDIA_DIR/" > /dev/null
    info "$name pushed"
  fi
done

# ---------------------------------------------------------------------------
# For each clip: start playback, then assert on what the player actually did.
# ---------------------------------------------------------------------------
check_clip() {
  local file="$1" expect_audio="$2" label="$3"
  local log="$OUT_DIR/mc-${label}.txt"

  say "$label  ($file)"

  sh_ am force-stop "$PKG_DEBUG"
  sleep 1
  adb_ logcat -c
  sh_ am start -a com.gan.spatialplayer.SMOKE_PLAY -n "$ACT_SMOKE" \
      --es smoke_path "$MEDIA_DIR/$file" --es smoke_mime "video/x-matroska" > /dev/null
  sleep 6

  "$ADB" logcat -d -v time > "$log" 2>/dev/null
  touch "$log"

  # 1. Did the FFmpeg decoder get selected for the audio track?
  if grep -qiE "FfmpegAudioRenderer|ffmpeg" "$log"; then
    pass "FFmpeg audio renderer engaged"
  else
    # Fall back to inference: if the platform has no decoder, ffmpeg must have been used.
    if grep -qiE "MediaCodecAudioRenderer" "$log"; then
      info "MediaCodec audio renderer referenced"
    fi
    fail "no FFmpeg audio renderer evidence"
  fi

  # 2. Channel count at the output. 0x3 = stereo, 0x3f = 5.1. This is the authoritative check
  #    that the multichannel signal survived decode instead of being folded down to stereo.
  local mask51
  mask51=$(sh_ dumpsys audio | grep -oE "channelMask=0x3f" | head -1)
  if [ -n "$mask51" ]; then
    pass "output configured for 5.1 (channelMask=0x3f)"
  else
    local masks
    masks=$(sh_ dumpsys audio | grep -oE "channelMask=0x[0-9a-fA-F]+" | tail -4 | sort -u | tr '\n' ' ')
    fail "no 5.1 output configuration seen (masks: ${masks:-none})"
  fi

  # 3. Spatialisation is *routing dependent*: Android only engages the spatializer on an output
  #    that advertises support. On the built-in speaker it legitimately stays off, so only require
  #    it when a headset is the active route.
  local spat active
  spat=$(sh_ dumpsys audio | grep -oE "isSpatialized=(true|false)" | tail -8 | sort | uniq -c | tr '\n' ' ')

  # Spatialisation is routing dependent, and the active media route is chosen by the system, not
  # by the app (Media3 1.8 has no preferred-device API). So distinguish "the headset is the active
  # media output" - where spatialisation is required - from "audio is on the speaker", where the
  # platform legitimately leaves the spatializer off and this check cannot mean anything.
  active=""
  if sh_ dumpsys audio | grep -qE "onRoutingUpdated: .*type:(bt_a2dp|ble_headset|wired_headphones|wired_headset|usb_headset)"; then
    if [ "$(sh_ dumpsys media.audio_flinger | grep -cE 'BT A2DP|A2DP Output' 2>/dev/null)" -gt 0 ] 2>/dev/null; then
      active="headset"
    fi
  fi
  # A connected (not merely paired) A2DP device is reported by the Bluetooth stack.
  if [ -z "$active" ] && sh_ dumpsys bluetooth_manager | grep -q "mA2dp.*STATE_CONNECTED\|StateMachine: Connected"; then
    active="headset"
  fi

  if echo "$spat" | grep -q "isSpatialized=true"; then
    pass "audio track reported spatialized=true  ($spat)"
  elif [ -n "$active" ]; then
    info "a headset appears active but the platform did not spatialise this track ($spat)"
    info "check Settings > Sound & vibration > Spatial audio is on for the media device"
  else
    skip "spatializer check (active media route is the built-in speaker, not a headset)"
  fi

  # 4. Decoder errors would show up here.
  if grep -qiE "FfmpegDecoderException|audio codec:|Decoder init failed" "$log"; then
    fail "decoder error reported"
    grep -iE "FfmpegDecoderException|audio codec:|Decoder init failed" "$log" | head -3 | sed 's/^/      /'
  else
    pass "no decoder errors"
  fi

  # 5. Confirm the process survived.
  if [ -n "$(sh_ pidof "$PKG_DEBUG")" ]; then
    pass "process alive"
  else
    fail "process died during playback"
  fi
}

check_clip "ac3_51_720p.mkv" "ac3" "ac3-51"
check_clip "truehd_51_720p.mkv" "truehd" "truehd-51"

# ---------------------------------------------------------------------------
# HDR: assert the player saw a 10-bit PQ stream rather than falling back to SDR.
# ---------------------------------------------------------------------------
say "hdr10 passthrough"
sh_ am force-stop "$PKG_DEBUG"
sleep 1
adb_ logcat -c
sh_ am start -a com.gan.spatialplayer.SMOKE_PLAY -n "$ACT_SMOKE" \
    --es smoke_path "$MEDIA_DIR/hdr10_hevc_720p.mkv" --es smoke_mime "video/x-matroska" > /dev/null
sleep 5
"$ADB" logcat -d -v time > "$OUT_DIR/mc-hdr10.txt" 2>/dev/null
touch "$OUT_DIR/mc-hdr10.txt"

if grep -qiE "hevc|h265|video/hevc" "$OUT_DIR/mc-hdr10.txt"; then
  pass "HEVC decoder engaged for the HDR10 stream"
else
  info "no explicit hevc line; see mc-hdr10.txt"
fi

# The panel's own HDR conversion mode tells us whether the system is tone mapping or passing through.
CONV=$(sh_ dumpsys display | grep -m1 -oE "mHdrConversionMode=HdrConversionMode\{[^}]*\}")
info "display HDR conversion: ${CONV:-unknown}"
if echo "$CONV" | grep -q "HDR_CONVERSION_SYSTEM"; then
  pass "system tone mapping active (HDR_CONVERSION_SYSTEM)"
elif echo "$CONV" | grep -q "HDR_CONVERSION_PASSTHROUGH"; then
  pass "HDR passthrough to the panel (HDR_CONVERSION_PASSTHROUGH)"
else
  info "conversion mode not recognised"
fi

# SurfaceFlinger reports the display's active HDR state via the HDR/SDR ratio.
RATIO=$(sh_ dumpsys display | grep -m1 -oE "hdrSdrRatio [0-9.]+")
info "display ${RATIO:-hdrSdrRatio unknown}"

# ---------------------------------------------------------------------------
# Subtitles: assert the text track is discovered, supported, and selectable.
#
# "Did a cue appear on screen" is not readable from logcat, so the check is on the track list:
# the SubRip track must be present, reported supported, and selecting it must flip it to selected.
# ---------------------------------------------------------------------------
say "subtitle track discovery and selection"
sh_ am force-stop "$PKG_DEBUG"
sleep 1
adb_ logcat -c
sh_ am start -a com.gan.spatialplayer.SMOKE_TRACKS -n "$ACT_TRACKS" \
    --es track_probe_path "$MEDIA_DIR/h264_aac_subs_720p.mkv" \
    --ez track_probe_select_text true > /dev/null
sleep 8
adb_ logcat -d -v time -s SpatialPlayerProbe > "$OUT_DIR/mc-subs.txt" 2>/dev/null
touch "$OUT_DIR/mc-subs.txt"

SUBS_LOG="$OUT_DIR/mc-subs.txt"

if grep -q "type=text|" "$SUBS_LOG"; then
  pass "subtitle track discovered"
  grep -oE "track :: type=text\|[^\n]*" "$SUBS_LOG" | head -1 | sed 's/^/      /'
else
  fail "no text track reported for a clip with an embedded SubRip stream"
fi

if grep -q "text_selected=1" "$SUBS_LOG"; then
  pass "subtitle track selectable (text_selected=1)"
else
  fail "subtitle track was not selected by the track override"
fi

# The multichannel clip must present as 6 channels, not a stereo downmix, or the spatializer has
# nothing to place.
say "multichannel track selection"
sh_ am force-stop "$PKG_DEBUG"
sleep 1
adb_ logcat -c
sh_ am start -a com.gan.spatialplayer.SMOKE_TRACKS -n "$ACT_TRACKS" \
    --es track_probe_path "$MEDIA_DIR/truehd_51_720p.mkv" > /dev/null
sleep 8
adb_ logcat -d -v time -s SpatialPlayerProbe > "$OUT_DIR/mc-trackselect.txt" 2>/dev/null
touch "$OUT_DIR/mc-trackselect.txt"

if grep -qE "6ch 5\.1" "$OUT_DIR/mc-trackselect.txt"; then
  pass "TrueHD selected as 6ch 5.1"
  grep -oE "selected_audio :: .*" "$OUT_DIR/mc-trackselect.txt" | head -1 | sed 's/^/      /'
else
  fail "TrueHD was not selected as a 5.1 track"
  grep -oE "selected_audio :: .*" "$OUT_DIR/mc-trackselect.txt" | head -1 | sed 's/^/      /'
fi

if grep -q "type=audio|selected=true" "$OUT_DIR/mc-trackselect.txt"; then
  pass "an audio track is selected"
else
  fail "no audio track selected"
fi

# ---------------------------------------------------------------------------
if grep -qiE "FATAL EXCEPTION|E AndroidRuntime" "$OUT_DIR"/mc-*.txt; then
  fail "fatal exception during multichannel tests"
  grep -hE "FATAL EXCEPTION|E AndroidRuntime" "$OUT_DIR"/mc-*.txt | head -5 | sed 's/^/      /'
else
  pass "no fatal exceptions"
fi

say "summary"
printf '  passed %d   failed %d   skipped %d\n' "$PASS" "$FAIL" "$SKIP"
printf '  artifacts: %s\n' "$OUT_DIR"
[ "$FAIL" -eq 0 ] || exit 1
